<?php

/* Diccionario de colores CSS estilo DreamWeaver */

return array(   array("Palabra" => "!important"                 , "Color" => "TxtRojo"),
    
                /*******************/
                /* Propiedades CSS */
                /*******************/
                array("Palabra" => "animation-delay"            , "Color" => "TxtAzul"),
                array("Palabra" => "animation-direction"        , "Color" => "TxtAzul"),
                array("Palabra" => "animation-duration"         , "Color" => "TxtAzul"),
                array("Palabra" => "animation-fill-mode"        , "Color" => "TxtAzul"),
                array("Palabra" => "animation-iteration-count"  , "Color" => "TxtAzul"),
                array("Palabra" => "animation-name"             , "Color" => "TxtAzul"),
                array("Palabra" => "animation-play-state"       , "Color" => "TxtAzul"),
                array("Palabra" => "animation-timing-function"  , "Color" => "TxtAzul"),
                array("Palabra" => "animation"                  , "Color" => "TxtAzul"),
    
                array("Palabra" => "border-bottom-color"        , "Color" => "TxtAzul"),
                array("Palabra" => "border-bottom-left-radius"  , "Color" => "TxtAzul"),
                array("Palabra" => "border-bottom-right-radius" , "Color" => "TxtAzul"),
                array("Palabra" => "border-bottom-style"        , "Color" => "TxtAzul"),
                array("Palabra" => "border-bottom"              , "Color" => "TxtAzul"),
                array("Palabra" => "border-color"               , "Color" => "TxtAzul"),
                array("Palabra" => "border-image-outset"        , "Color" => "TxtAzul"),
                array("Palabra" => "border-image-repeat"        , "Color" => "TxtAzul"),
                array("Palabra" => "border-image-slice"         , "Color" => "TxtAzul"),
                array("Palabra" => "border-image-source"        , "Color" => "TxtAzul"),
                array("Palabra" => "border-image-width"         , "Color" => "TxtAzul"),
                array("Palabra" => "border-image"               , "Color" => "TxtAzul"),
                array("Palabra" => "border-left-color"          , "Color" => "TxtAzul"),
                array("Palabra" => "border-left-style"          , "Color" => "TxtAzul"),
                array("Palabra" => "border-left-width"          , "Color" => "TxtAzul"),
                array("Palabra" => "border-left"                , "Color" => "TxtAzul"),
                array("Palabra" => "border-radius"              , "Color" => "TxtAzul"),
                array("Palabra" => "border-right-color"         , "Color" => "TxtAzul"),
                array("Palabra" => "border-right-style"         , "Color" => "TxtAzul"),
                array("Palabra" => "border-right-width"         , "Color" => "TxtAzul"),
                array("Palabra" => "border-right"               , "Color" => "TxtAzul"),
                array("Palabra" => "border-top-color"           , "Color" => "TxtAzul"),
                array("Palabra" => "border-top-left-radius"     , "Color" => "TxtAzul"),
                array("Palabra" => "border-top-right-radius"    , "Color" => "TxtAzul"),
                array("Palabra" => "border-top-style"           , "Color" => "TxtAzul"),
                array("Palabra" => "border-top-width"           , "Color" => "TxtAzul"),
                array("Palabra" => "border-top"                 , "Color" => "TxtAzul"),
                array("Palabra" => "border-width"               , "Color" => "TxtAzul"),
                array("Palabra" => "border-collapse"            , "Color" => "TxtAzul"),
                array("Palabra" => "border-spacing"             , "Color" => "TxtAzul"),
                array("Palabra" => "border-style"               , "Color" => "TxtAzul"),
                array("Palabra" => "border"                     , "Color" => "TxtAzul"),

                array("Palabra" => "outline"                    , "Color" => "TxtAzul"),

                array("Palabra" => "box-shadow"                 , "Color" => "TxtAzul"),
                array("Palabra" => "break-after"                , "Color" => "TxtAzul"),
                array("Palabra" => "break-before"               , "Color" => "TxtAzul"),
                array("Palabra" => "break-inside"               , "Color" => "TxtAzul"),
                array("Palabra" => "overflow"                   , "Color" => "TxtAzul"),
                array("Palabra" => "overflow-x"                 , "Color" => "TxtAzul"),
                array("Palabra" => "overflow-y"                 , "Color" => "TxtAzul"),
                
                array("Palabra" => "overflow-y"                 , "Color" => "TxtAzul"),
    
                array("Palabra" => "align-content"              , "Color" => "TxtAzul"),
                array("Palabra" => "align-items"                , "Color" => "TxtAzul"),
                array("Palabra" => "align-self"                 , "Color" => "TxtAzul"),
                array("Palabra" => "box-decoration-break"       , "Color" => "TxtAzul"),
                array("Palabra" => "flex-basis"                 , "Color" => "TxtAzul"),
                array("Palabra" => "flex-direction"             , "Color" => "TxtAzul"),
                array("Palabra" => "flex-flow"                  , "Color" => "TxtAzul"),
                array("Palabra" => "flex-grow"                  , "Color" => "TxtAzul"),
                array("Palabra" => "flex-shrink"                , "Color" => "TxtAzul"),
                array("Palabra" => "flex-wrap"                  , "Color" => "TxtAzul"),
                array("Palabra" => "flex"                       , "Color" => "TxtAzul"),
                array("Palabra" => "justify-content"            , "Color" => "TxtAzul"),
                array("Palabra" => "order"                      , "Color" => "TxtAzul"),

                array("Palabra" => "opacity"                    , "Color" => "TxtAzul"),

                array("Palabra" => "columns-count"              , "Color" => "TxtAzul"),
                array("Palabra" => "columns-fill"               , "Color" => "TxtAzul"),
                array("Palabra" => "columns-gap"                , "Color" => "TxtAzul"),
                array("Palabra" => "columns-rule-color"         , "Color" => "TxtAzul"),
                array("Palabra" => "columns-rule-style"         , "Color" => "TxtAzul"),
                array("Palabra" => "columns-rule-width"         , "Color" => "TxtAzul"),
                array("Palabra" => "columns-rule"               , "Color" => "TxtAzul"),
                array("Palabra" => "columns-span"               , "Color" => "TxtAzul"),
                array("Palabra" => "columns-width"              , "Color" => "TxtAzul"),
                array("Palabra" => "columns"                    , "Color" => "TxtAzul"),

                array("Palabra" => "hyphens"                    , "Color" => "TxtAzul"),
                array("Palabra" => "marks"                      , "Color" => "TxtAzul"),
    
                array("Palabra" => "content-increment"          , "Color" => "TxtAzul"),
                array("Palabra" => "content-reset"              , "Color" => "TxtAzul"),
                array("Palabra" => "content"                    , "Color" => "TxtAzul"),
                array("Palabra" => "quotes"                     , "Color" => "TxtAzul"),
    
                array("Palabra" => "background-attachment"      , "Color" => "TxtAzul"),
                array("Palabra" => "background-clip"            , "Color" => "TxtAzul"),
                array("Palabra" => "background-color"           , "Color" => "TxtAzul"),
                array("Palabra" => "background-image"           , "Color" => "TxtAzul"),
                array("Palabra" => "background-origin"          , "Color" => "TxtAzul"),
                array("Palabra" => "background-position"        , "Color" => "TxtAzul"),
                array("Palabra" => "background-repeat"          , "Color" => "TxtAzul"),
                array("Palabra" => "background-size"            , "Color" => "TxtAzul"),
                array("Palabra" => "background"                 , "Color" => "TxtAzul"),

                array("Palabra" => "font-family"                , "Color" => "TxtAzul"),
                array("Palabra" => "font-feature-settings"      , "Color" => "TxtAzul"),
                array("Palabra" => "font-size"                  , "Color" => "TxtAzul"),
                array("Palabra" => "font-size-adjust"           , "Color" => "TxtAzul"),
                array("Palabra" => "font-stretch"               , "Color" => "TxtAzul"),
                array("Palabra" => "font-style"                 , "Color" => "TxtAzul"),
                array("Palabra" => "font-variant"               , "Color" => "TxtAzul"),
                array("Palabra" => "font-weight"                , "Color" => "TxtAzul"),
                array("Palabra" => "font"                       , "Color" => "TxtAzul"),
    
                array("Palabra" => "image-rendering"            , "Color" => "TxtAzul"),
                array("Palabra" => "image-orientation"          , "Color" => "TxtAzul"),
    
                array("Palabra" => "orphans"                    , "Color" => "TxtAzul"),
                array("Palabra" => "page-break-after"           , "Color" => "TxtAzul"),
                array("Palabra" => "page-break-before"          , "Color" => "TxtAzul"),
                array("Palabra" => "page-break-inside"          , "Color" => "TxtAzul"),
                array("Palabra" => "windows"                    , "Color" => "TxtAzul"),
        
                array("Palabra" => "box-sizing"                 , "Color" => "TxtAzul"),
                array("Palabra" => "cursor"                     , "Color" => "TxtAzul"),
                array("Palabra" => "filter"                     , "Color" => "TxtAzul"),
                array("Palabra" => "icon"                       , "Color" => "TxtAzul"),
                array("Palabra" => "ime-mode"                   , "Color" => "TxtAzul"),
                array("Palabra" => "resize"                     , "Color" => "TxtAzul"),
                array("Palabra" => "user-select"                , "Color" => "TxtAzul"),
    
                array("Palabra" => "margin-bottom"              , "Color" => "TxtAzul"),
                array("Palabra" => "margin-left"                , "Color" => "TxtAzul"),
                array("Palabra" => "margin-right"               , "Color" => "TxtAzul"),
                array("Palabra" => "margin-top"                 , "Color" => "TxtAzul"),
                array("Palabra" => "margin"                     , "Color" => "TxtAzul"),
    
                array("Palabra" => "list-style-image"           , "Color" => "TxtAzul"),
                array("Palabra" => "list-style-position"        , "Color" => "TxtAzul"),
                array("Palabra" => "list-style-type"            , "Color" => "TxtAzul"),
                array("Palabra" => "list-style"                 , "Color" => "TxtAzul"),
    
                array("Palabra" => "bottom"                     , "Color" => "TxtAzul"),
                array("Palabra" => "clear"                      , "Color" => "TxtAzul"),
                array("Palabra" => "clip"                       , "Color" => "TxtAzul"),
                array("Palabra" => "display"                    , "Color" => "TxtAzul"),
                array("Palabra" => "float"                      , "Color" => "TxtAzul"),
                array("Palabra" => "left"                       , "Color" => "TxtAzul"),
                array("Palabra" => "position"                   , "Color" => "TxtAzul"),
                array("Palabra" => "right"                      , "Color" => "TxtAzul"),
                array("Palabra" => "top"                        , "Color" => "TxtAzul"),
                array("Palabra" => "visibility"                 , "Color" => "TxtAzul"),
    
                array("Palabra" => "padding-bottom"             , "Color" => "TxtAzul"),
                array("Palabra" => "padding-left"               , "Color" => "TxtAzul"),
                array("Palabra" => "padding-right"              , "Color" => "TxtAzul"),
                array("Palabra" => "padding-top"                , "Color" => "TxtAzul"),
                array("Palabra" => "padding"                    , "Color" => "TxtAzul"),
    
                array("Palabra" => "mask-type"                  , "Color" => "TxtAzul"),
                array("Palabra" => "mask"                       , "Color" => "TxtAzul"),
                array("Palabra" => "pointer-events"             , "Color" => "TxtAzul"),
                array("Palabra" => "text-rendering"             , "Color" => "TxtAzul"),

                array("Palabra" => "src"                        , "Color" => "TxtAzul"),
    
/*              array("Palabra" => "border-collapse"            , "Color" => "TxtAzul"),
                array("Palabra" => "border-spacing"             , "Color" => "TxtAzul"),
                array("Palabra" => "border-style"               , "Color" => "TxtAzul"),*/
                array("Palabra" => "caption-side"               , "Color" => "TxtAzul"),
                array("Palabra" => "empty-cells"                , "Color" => "TxtAzul"),
                array("Palabra" => "table-layout"               , "Color" => "TxtAzul"),
    
                array("Palabra" => "max-height"                 , "Color" => "TxtAzul"),
                array("Palabra" => "max-width"                  , "Color" => "TxtAzul"),
                array("Palabra" => "min-height"                 , "Color" => "TxtAzul"),
                array("Palabra" => "min-width"                  , "Color" => "TxtAzul"),
                array("Palabra" => "height"                     , "Color" => "TxtAzul"),
                array("Palabra" => "width"                      , "Color" => "TxtAzul"),
    
                array("Palabra" => "color"                      , "Color" => "TxtAzul"),
                array("Palabra" => "direction"                  , "Color" => "TxtAzul"),
                array("Palabra" => "letter-spacing"             , "Color" => "TxtAzul"),
                array("Palabra" => "line-height"                , "Color" => "TxtAzul"),
                array("Palabra" => "tab-size"                   , "Color" => "TxtAzul"),
                array("Palabra" => "text-align-last"            , "Color" => "TxtAzul"),
                array("Palabra" => "text-align"                 , "Color" => "TxtAzul"),
                array("Palabra" => "text-decoration-color"      , "Color" => "TxtAzul"),
                array("Palabra" => "text-decoration-line"       , "Color" => "TxtAzul"),
                array("Palabra" => "text-decoration-style"      , "Color" => "TxtAzul"),
                array("Palabra" => "text-decoration"            , "Color" => "TxtAzul"),
                array("Palabra" => "text-ident"                 , "Color" => "TxtAzul"),
                array("Palabra" => "text-justify"               , "Color" => "TxtAzul"),
                array("Palabra" => "text-overflow"              , "Color" => "TxtAzul"),
                array("Palabra" => "text-shadow"                , "Color" => "TxtAzul"),
                array("Palabra" => "text-transform"             , "Color" => "TxtAzul"),
                array("Palabra" => "text-underline-position"    , "Color" => "TxtAzul"),
                array("Palabra" => "unicode-bidi"               , "Color" => "TxtAzul"),
                array("Palabra" => "unicode-range"              , "Color" => "TxtAzul"),
                array("Palabra" => "vertical-align"             , "Color" => "TxtAzul"),
                array("Palabra" => "white-space"                , "Color" => "TxtAzul"),
                array("Palabra" => "word-break"                 , "Color" => "TxtAzul"),
                array("Palabra" => "word-spacing"               , "Color" => "TxtAzul"),
                array("Palabra" => "word-wrap"                  , "Color" => "TxtAzul"),
                array("Palabra" => "z-index"                    , "Color" => "TxtAzul"),
    
                array("Palabra" => "backface-visibility"        , "Color" => "TxtAzul"),
                array("Palabra" => "perspective-origin"         , "Color" => "TxtAzul"),
                array("Palabra" => "perspective"                , "Color" => "TxtAzul"),
                array("Palabra" => "transform-origin"           , "Color" => "TxtAzul"),
                array("Palabra" => "transform-style"            , "Color" => "TxtAzul"),
                array("Palabra" => "transform"                  , "Color" => "TxtAzul"),

                array("Palabra" => "transition-delay"           , "Color" => "TxtAzul"),
                array("Palabra" => "transition-duration"        , "Color" => "TxtAzul"),
                array("Palabra" => "transition-position"        , "Color" => "TxtAzul"),
                array("Palabra" => "transition-property"        , "Color" => "TxtAzul"),
                array("Palabra" => "transition-timing-function" , "Color" => "TxtAzul"),
                array("Palabra" => "transition"                 , "Color" => "TxtAzul"),

                /******************/
                /* Etiquetas HTML */
                /******************/
                array("Palabra" => "body"                       , "Color" => "TxtVerde"),
                array("Palabra" => "section"                    , "Color" => "TxtVerde"),
                array("Palabra" => "nav"                        , "Color" => "TxtVerde"),
                array("Palabra" => "article"                    , "Color" => "TxtVerde"),
                array("Palabra" => "aside"                      , "Color" => "TxtVerde"),
                array("Palabra" => "h1"                         , "Color" => "TxtVerde"),
                array("Palabra" => "h2"                         , "Color" => "TxtVerde"),
                array("Palabra" => "h3"                         , "Color" => "TxtVerde"),
                array("Palabra" => "h4"                         , "Color" => "TxtVerde"),
                array("Palabra" => "h5"                         , "Color" => "TxtVerde"),
                array("Palabra" => "h6"                         , "Color" => "TxtVerde"),
                array("Palabra" => "header"                     , "Color" => "TxtVerde"),
                array("Palabra" => "footer"                     , "Color" => "TxtVerde"),
                array("Palabra" => "address"                    , "Color" => "TxtVerde"),
                array("Palabra" => "main"                       , "Color" => "TxtVerde"),
                
                array("Palabra" => "p"                          , "Color" => "TxtVerde"),
                array("Palabra" => "hr"                         , "Color" => "TxtVerde"),
                array("Palabra" => "pre"                        , "Color" => "TxtVerde"),
                array("Palabra" => "blockquote"                 , "Color" => "TxtVerde"),
                array("Palabra" => "ol"                         , "Color" => "TxtVerde"),
                array("Palabra" => "ul"                         , "Color" => "TxtVerde"),
                array("Palabra" => "li"                         , "Color" => "TxtVerde"),
                array("Palabra" => "dl"                         , "Color" => "TxtVerde"),
                array("Palabra" => "dt"                         , "Color" => "TxtVerde"),
                array("Palabra" => "dd"                         , "Color" => "TxtVerde"),
                array("Palabra" => "figure"                     , "Color" => "TxtVerde"),
                array("Palabra" => "figcaption"                 , "Color" => "TxtVerde"),
                array("Palabra" => "div"                        , "Color" => "TxtVerde"),
     
                array("Palabra" => "a"                          , "Color" => "TxtVerde"),
                array("Palabra" => "em"                         , "Color" => "TxtVerde"),
                array("Palabra" => "strong"                     , "Color" => "TxtVerde"),
                array("Palabra" => "small"                      , "Color" => "TxtVerde"),
                array("Palabra" => "s"                          , "Color" => "TxtVerde"),
                array("Palabra" => "cite"                       , "Color" => "TxtVerde"),
                array("Palabra" => "q"                          , "Color" => "TxtVerde"),
                array("Palabra" => "dfn"                        , "Color" => "TxtVerde"),
                array("Palabra" => "abbr"                       , "Color" => "TxtVerde"),
                array("Palabra" => "data"                       , "Color" => "TxtVerde"),
                array("Palabra" => "time"                       , "Color" => "TxtVerde"),
                array("Palabra" => "code"                       , "Color" => "TxtVerde"),
                array("Palabra" => "var"                        , "Color" => "TxtVerde"),
                array("Palabra" => "samp"                       , "Color" => "TxtVerde"),
                array("Palabra" => "kbd"                        , "Color" => "TxtVerde"),
                array("Palabra" => "sub"                        , "Color" => "TxtVerde"),
                array("Palabra" => "sup"                        , "Color" => "TxtVerde"),
                array("Palabra" => "i"                          , "Color" => "TxtVerde"),
                array("Palabra" => "b"                          , "Color" => "TxtVerde"),
                array("Palabra" => "u"                          , "Color" => "TxtVerde"),
                array("Palabra" => "mark"                       , "Color" => "TxtVerde"),
                array("Palabra" => "ruby"                       , "Color" => "TxtVerde"),
                array("Palabra" => "rt"                         , "Color" => "TxtVerde"),
                array("Palabra" => "rp"                         , "Color" => "TxtVerde"),
                array("Palabra" => "bdi"                        , "Color" => "TxtVerde"),
                array("Palabra" => "bdo"                        , "Color" => "TxtVerde"),
                array("Palabra" => "span"                       , "Color" => "TxtVerde"),
                array("Palabra" => "br"                         , "Color" => "TxtVerde"),
                array("Palabra" => "wbr"                        , "Color" => "TxtVerde"),

                array("Palabra" => "img"                        , "Color" => "TxtVerde"),
                array("Palabra" => "iframe"                     , "Color" => "TxtVerde"),
                array("Palabra" => "embed"                      , "Color" => "TxtVerde"),
                array("Palabra" => "object"                     , "Color" => "TxtVerde"),
                array("Palabra" => "param"                      , "Color" => "TxtVerde"),
                array("Palabra" => "video"                      , "Color" => "TxtVerde"),
                array("Palabra" => "audio"                      , "Color" => "TxtVerde"),
                array("Palabra" => "source"                     , "Color" => "TxtVerde"),
                array("Palabra" => "track"                      , "Color" => "TxtVerde"),
                array("Palabra" => "canvas"                     , "Color" => "TxtVerde"),
                array("Palabra" => "map"                        , "Color" => "TxtVerde"),
                array("Palabra" => "area"                       , "Color" => "TxtVerde"),
                array("Palabra" => "svg"                        , "Color" => "TxtVerde"),
                array("Palabra" => "match"                      , "Color" => "TxtVerde"),

                array("Palabra" => "table"                      , "Color" => "TxtVerde"),
                array("Palabra" => "caption"                    , "Color" => "TxtVerde"),
                array("Palabra" => "colgroup"                   , "Color" => "TxtVerde"),
                array("Palabra" => "col"                        , "Color" => "TxtVerde"),
                array("Palabra" => "tbody"                      , "Color" => "TxtVerde"),
                array("Palabra" => "thead"                      , "Color" => "TxtVerde"),
                array("Palabra" => "tfoot"                      , "Color" => "TxtVerde"),
                array("Palabra" => "tr"                         , "Color" => "TxtVerde"),
                array("Palabra" => "td"                         , "Color" => "TxtVerde"),
                array("Palabra" => "th"                         , "Color" => "TxtVerde"),
    
                array("Palabra" => "form"                       , "Color" => "TxtVerde"),
                array("Palabra" => "fieldset"                   , "Color" => "TxtVerde"),
                array("Palabra" => "legend"                     , "Color" => "TxtVerde"),
                array("Palabra" => "label"                      , "Color" => "TxtVerde"),
                array("Palabra" => "input"                      , "Color" => "TxtVerde"),
                array("Palabra" => "button"                     , "Color" => "TxtVerde"),
                array("Palabra" => "select"                     , "Color" => "TxtVerde"),
                array("Palabra" => "datalist"                   , "Color" => "TxtVerde"),
                array("Palabra" => "optgroup"                   , "Color" => "TxtVerde"),
                array("Palabra" => "textarea"                   , "Color" => "TxtVerde"),
                array("Palabra" => "keygen"                     , "Color" => "TxtVerde"),
                array("Palabra" => "output"                     , "Color" => "TxtVerde"),
                array("Palabra" => "progress"                   , "Color" => "TxtVerde"),
                array("Palabra" => "meter"                      , "Color" => "TxtVerde"),
    
                array("Palabra" => "details"                    , "Color" => "TxtVerde"),
                array("Palabra" => "sumary"                     , "Color" => "TxtVerde"),
                array("Palabra" => "command"                    , "Color" => "TxtVerde"),
                array("Palabra" => "menu"                       , "Color" => "TxtVerde"),
    
                /* Los estados SIEMPRE deben estar al final del array y con el mismo orden */
                array("RESERVADO"           => ""               , "Color" => "TxtNegro"),       // count-10
                array("RESERVADO"           => ""               , "Color" => "TxtNegro"),       // count-9 
                array("Estado_Selector"     => ""               , "Color" => "TxtVerde"),       // count-8 (Selector)
                array("Estado_Valor"        => ""               , "Color" => "TxtNegro"),       // count-7 (Valor)       UNUSED
                array("Estado_Propiedad"    => ""               , "Color" => "TxtAzul"),        // count-6 (Propiedades) UNUSED
                array("Estado_Normal"       => ""               , "Color" => "TxtNegro"),       // count-5
                array("Estado_Comentarios"  => ""               , "Color" => "TxtGris"),        // count-4
                array("Estado_String"       => ""               , "Color" => "TxtAmarillo"),    // count-3
                array("Estado_Variable"     => ""               , "Color" => "TxtMarron"),      // count-2 (Reglas)
                array("Estado_Numero"       => ""               , "Color" => "TxtRojo")         // count-1
        
);
