<?php
    /* Tipo puede ser : 'Articulo' y 'EjemploLab' */

/* No poden haber 2 entrades amb la mateixa url o els butons siguiente y anterior entren en bucle infinit */
    return array(
/*	
array(  "Titulo"	=> "Tutorial JavaScript 1 Empezando",
        "Fecha" 	=> "26/07/2014", 
        "URL" 		=> "tutorial-javascript-emepzando",
        "Tags" 		=> array("HTML", "JavaScript", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Sqlite.png"),
*/
array(	"Titulo" 	=> "FlexBox y documentos responsive", 
        "Fecha" 	=> "25/07/2014",
        "URL" 		=> "flex-box-y-media-queries",
        "Tags" 		=> array("CSS", "HTML", "Programación", "Responsive"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Empezando con SQLite en C++",
        "Fecha" 	=> "22/05/2014",
        "URL" 		=> "empezando-sqlte-c",
        "Tags" 		=> array("C y C++", "SQL", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Sqlite.png"),

array(	"Titulo" 	=> "Varios ejemplos de menús",
        "Fecha" 	=> "19/02/2014" ,
        "URL" 		=> "varios-ejemplos-de-menus",
        "Tags" 		=> array("CSS", "HTML", "JQuery", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "VariosMenus.png"),

array(	"Titulo" 	=> "Varios servidores web apache de pruebas",
        "Fecha" 	=> "15/02/2014" ,
        "URL" 		=> "varios-servidores-web-apache-de-pruebas",
        "Tags" 		=> array("Apache", "Servidores", "Windows", "Linux"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "XAMPP.png"),

array(	"Titulo" 	=> "Tablas automáticas y tablas fijas",
        "Fecha" 	=> "12/01/2014" ,
        "URL" 		=> "Tablas",
        "Tags" 		=> array("CSS", "HTML", "Programación", "Responsive"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Referéncia CSS : Propiedades",
        "Fecha" 	=> "27/06/2013" ,
        "URL" 		=> "PropiedadesCSS",
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "USB booteable con varios sistemas operativos (ACTUALIZADO)"		,
        "Fecha" 	=> "16/05/2013" ,
        "URL" 		=> "USB_Boot" 										,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "USBBoot.png"),

array(	"Titulo" 	=> "Referéncia CSS : Degradados" 									,
        "Fecha" 	=> "11/03/2013" ,
        "URL" 		=> "DegradadosCSS" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Animaciones CSS3" 												,
        "Fecha" 	=> "29/01/2013" ,
        "URL" 		=> "AnimacionesCSS3" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "devildrey33_ListaDesplegable 2.0 FINAL" 							,
        "Fecha" 	=> "20/01/2013" ,
        "URL" 		=> "devildrey33_ListaDesplegable_2-0" 				,
        "Tags" 		=> array("JavaScript", "HTML", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "devildrey33_ListaDesplegable_2.0.png"),

array(	"Titulo" 	=> "devildrey33_ListaDesplegable 2.0 BETA" 							,
        "Fecha" 	=> "05/01/2013" ,
        "URL" 		=> "devildrey33_ListaDesplegable_2-0_BETA" 			,
        "Tags" 		=> array("JavaScript", "HTML", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "devildrey33_ListaDesplegable_2.0.png"),

array(	"Titulo" 	=> "Referéncia CSS : Unidades" 										,
        "Fecha" 	=> "05/12/2012" ,
        "URL" 		=> "UnidadesCSS"										,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Referéncia CSS : Colores" 										,
        "Fecha" 	=> "04/12/2012" ,
        "URL" 		=> "ColoresCSS"										,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Atributo ContentEditable del HTML" 								,
        "Fecha" 	=> "21/11/2012" ,
        "URL" 		=> "ContentEditable" 									,
        "Tags" 		=> array("JavaScript", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ContentEditable.png"),

array(	"Titulo" 	=> "Añadir más seguridad a nuestro servidor Web" 					,
        "Fecha" 	=> "29/10/2012" ,
        "URL" 		=> "SeguridadServidorWeb" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "Servidores", ".htaccess") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Candado.png"),

array(	"Titulo" 	=> "Referéncia CSS : Selectores" 									,
        "Fecha" 	=> "17/10/2012" ,
        "URL" 		=> "SelectoresCSS" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

/*array(	"Titulo" 	=> "USB booteable con varios sistemas operativos" 					,
        "Fecha" 	=> "26/09/2012" ,
        "URL" 		=> "USB_Boot" 										,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "USBBoot.png"),*/

array(	"Titulo" 	=> "DWL 2012 [15/02/2012]" 											,
        "Fecha" 	=> "15/02/2012" ,
        "URL" 		=> "DWL2012-15-02-2012" 								,
        "Tags" 		=> array("C y C++", "Windows", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ataque.png"),

/*array(	"Titulo" 	=> "DWL 2012 [08/02/2012]",
        "Fecha" 	=> "08/02/2012" ,
        "URL" 		=> "DWL2012-08-02-2012" 								,
        "Tags" 		=> array("C y C++", "Windows", "Programación"),	
        "Tipo"		=> "Articulo",
        "Imagen"	=> "DWL2012.png"),*/

array(	"Titulo" 	=> "Captchas (3 Captcha arrastrar y soltar PHP + JQuery)" 			,
        "Fecha" 	=> "05/12/2011" ,
        "URL" 		=> "Captcha3" 										,
        "Tags" 		=> array("PHP", "JQuery", "Programación", "HTML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Captcha3.png"),

array(	"Titulo" 	=> "Captchas (2 Captcha básico con php)"								,
        "Fecha" 	=> "04/12/2011" ,
        "URL" 		=> "Captcha2" 										,
        "Tags" 		=> array("PHP", "JavaScript", "Programación", "HTML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Captcha2.png"),

array(	"Titulo" 	=> "Captchas (1 Introducción)" 										,
        "Fecha" 	=> "03/12/2011" ,
        "URL" 		=> "Captcha1" 										,
        "Tags" 		=> array("PHP", "JavaScript", "Programación", "HTML") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Captcha.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (9 Tipografías)" 				,
        "Fecha" 	=> "28/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_9" 								,
        "Tags" 		=> array("HTML"), 
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5_9.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (8 Menus)" 					,
        "Fecha" 	=> "22/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_8" 								,
        "Tags" 		=> array("HTML", "CSS"), 
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5_8"),

array(	"Titulo" 	=> "Menu PHP + XML + JQuery + JavaScript + CSS" 						,
        "Fecha" 	=> "17/11/2011" ,
        "URL" 		=> "MenuWebFijo" 										,
        "Tags" 		=> array("HTML", "PHP", "JQuery", "Programación", "XML") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "MenuWebFijo"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 4 (imagenes)" 						,
        "Fecha" 	=> "16/11/2011" ,
        "URL" 		=> "Canvas2D_4" 										,
        "Tags" 		=> array("HTML", "Canvas2D", "JavaScript", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Canvas2D_4.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (7 Botones)"					,
        "Fecha" 	=> "15/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_7" 								,
        "Tags" 		=> array("HTML", "CSS"), 
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5_7.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (6 Diseño)" 					,
        "Fecha" 	=> "11/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_6" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (5 Más sobre los estilos)" 	,
        "Fecha" 	=> "10/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_5" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (4 Estilos)" 					,
        "Fecha" 	=> "09/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_4" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (3 Varias etiquetas)"			,
        "Fecha" 	=> "08/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_3" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (2 Empezando)" 				,
        "Fecha" 	=> "07/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_2" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (1 Introducción)" 			,
        "Fecha" 	=> "06/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_1" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "CSS3 : Efecto bola expandible" 									,
        "Fecha" 	=> "04/11/2011" ,
        "URL" 		=> "CSS3_BolaExpandible"								,
        "Tags" 		=> array("HTML", "CSS", "Programación"), 
        "Tipo"		=> "Articulo",
        "Imagen"	=> "BolaExpandible.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 3 (degradado lineal)" 				,
        "Fecha" 	=> "03/11/2011" ,
        "URL" 		=> "Canvas2D_3" 										,
        "Tags" 		=> array("HTML", "Canvas2D", "JavaScript", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Canvas2D_3.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 2 (texto)" 						,
        "Fecha" 	=> "02/11/2011" ,
        "URL" 		=> "Canvas2D_2" 										,
        "Tags" 		=> array("HTML", "Canvas2D", "JavaScript", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Canvas2D_2.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 1" 								,
        "Fecha" 	=> "31/10/2011" ,
        "URL" 		=> "Canvas2D_1" 										,
        "Tags" 		=> array("HTML", "Canvas2D", "JavaScript", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Canvas2D_1.png"),

array(	"Titulo" 	=> "CSS3 : Sombras y bordes redondeados" 							,
        "Fecha" 	=> "28/10/2011" ,
        "URL" 		=> "CSS3_Sombras_Bordes" 								,
        "Tags" 		=> array("HTML", "CSS", "Programación"), 
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

/*array(	"Titulo" 	=> "Varios retoques en la web de devildrey33" 						,
        "Fecha" 	=> "27/10/2011" ,
        "URL" 		=> "RetoquesWeb" 										,
        "Tags" 		=> array() ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Tridente.png"),*/

array(	"Titulo" 	=> "Instalar NetBeans y MinGW en Windows" 							,
        "Fecha" 	=> "26/10/2011" ,
        "URL" 		=> "NetBeansWindows"									,
        "Tags" 		=> array("Windows", "C y C++", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "NetBeans.png"),

array(	"Titulo" 	=> "PHP : Objeto devildrey33_PintarCodigo" 							,
        "Fecha" 	=> "25/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_devildrey33_PintarCodigo" 		,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "PHP.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 6 HTML)" 							,
        "Fecha" 	=> "24/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_HTML" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresHTML.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 5 Cpp)"							,
        "Fecha" 	=> "21/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_CPP" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresCPP.png"),

/*array(	"Titulo" 	=> "Buscador de texto en PHP" 										,
        "Fecha" 	=> "20/10/2011" ,
        "URL" 		=> "BuscadorPHP" 										,
        "Tags" 		=> array("PHP", "HTML", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "BuscarPHP.png"),*/

array(	"Titulo" 	=> "Colorear código con PHP (Parte 4 PHP)" 							,
        "Fecha" 	=> "19/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_PHP" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresPHP.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 3 JavaScript)" 					,
        "Fecha" 	=> "18/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_JavaScript" 					,
        "Tags" 		=> array("PHP", "HTML", "Programación", "JavaScript"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresJavaScript.png"),

array(	"Titulo" 	=> "CSS3 Transition y Transform" 									,
        "Fecha" 	=> "17/10/2011" ,
        "URL" 		=> "CSS3_Transition_Transform"						,
        "Tags" 		=> array("HTML", "Programación", "CSS"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 2 CSS)" 							,
        "Fecha" 	=> "14/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_CSS" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "CSS") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresCSS.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 1 XML)" 							,
        "Fecha" 	=> "13/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_XML"							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "XML"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ColoresXML.png"),

array(	"Titulo" 	=> "Generar un .lib a partir de una DLL con Visual Studio" 			,
        "Fecha" 	=> "12/10/2011" ,
        "URL" 		=> "GenerarLibDesdeDll" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "GenerarLibDesdeDll.png"),

array(	"Titulo" 	=> "Utilizar archivos XML con PHP" 									,
        "Fecha" 	=> "10/10/2011" ,
        "URL" 		=> "PHPyXML" 											,
        "Tags" 		=> array("PHP", "HTML", "XML", "Programación") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "PHPyXML.png"),

array(	"Titulo" 	=> "Crear servidor web de pruebas portatil para windows" 			,
        "Fecha" 	=> "07/10/2011" ,
        "URL" 		=> "XamppUSB" 										,
        "Tags" 		=> array("Windows", "Servidores", "HTML") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "XAMPP.png"),

array(	"Titulo" 	=> "Creación de feeds RSS" 											,
        "Fecha" 	=> "06/10/2011" ,
        "URL" 		=> "FeedsRSS" 										,
        "Tags" 		=> array("Apache", "PHP", "Programación", "HTML") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "RSS.png"),

array(	"Titulo" 	=> "Tutorial C++ 4 Creación de archivos DUMP"						,
        "Fecha" 	=> "05/10/2011" ,
        "URL" 		=> "Tutorial_WINAPI_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "DUMP.png"),

array(	"Titulo" 	=> "ComboBox PHP + JQuery + JavaScript + Css" 						,
        "Fecha" 	=> "04/10/2011" ,
        "URL" 		=> "ComboBoxWeb" 										,
        "Tags" 		=> array("PHP", "Programación", "JavaScript", "HTML") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ComboBoxWeb.png"),

array(	"Titulo" 	=> "Instalar Ubuntu bajo VirtualBox en Windows" 						,
        "Fecha" 	=> "03/10/2011" ,
        "URL" 		=> "InstalarUbuntuVirtualBox" 						,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "VirtualBox.png"),

array(	"Titulo" 	=> "WebGL" 															,
        "Fecha" 	=> "10/04/2011" ,
        "URL" 		=> "WebGL" 											,
        "Tags" 		=> array("HTML", "Programación", "JavaScript") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "WebGL.png"),

array(	"Titulo" 	=> "Inyección SQL" 													,
        "Fecha" 	=> "26/02/2011" ,
        "URL" 		=> "InyeccionSQL" 									,
        "Tags" 		=> array("HTML", "Programación", "PHP", "SQL") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "InyeccionSQL.png"),

array(	"Titulo" 	=> "Conversor UTF8 Windows1252" 										,
        "Fecha" 	=> "07/02/2011" ,
        "URL" 		=> "Conversor_UTF8_Windows1252" 						,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "ConversorUTF8-Windows1252.png"),

array(	"Titulo" 	=> "Comparativa de navegadores (enero 2011)" 						,
        "Fecha" 	=> "14/01/2011" ,
        "URL" 		=> "ComparativaNavegadoresEnero2011" 					,
        "Tags" 		=> array("HTML", "Programación"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Navegadores.png"),

/*array(	"Titulo" 	=> "DWL 0.961" 														,
        "Fecha" 	=> "27/11/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "DWL.png"),*/

array(	"Titulo" 	=> "BubaTronik 0.61" 												,
        "Fecha" 	=> "26/11/2010" ,
        "URL" 		=> "BubaTronik"										,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Articulo",
        "Imagen"	=> "BubaTronik061.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.11 Terminando el ensamblador" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_11" 							,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.11.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.10 Terminando el instalador" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_10" 							,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.0.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.9 Creación del ObjetoZLib" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_9" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.9.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.8 Creación del ObjetoTreeView" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_8" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.8.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.7 Creación del ObjetoListView" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_7" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.7.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.6 Creación del ObjetoProgressBar" 				,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_6" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.6.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.5 Creación del ObjetoComboBox"					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_5" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.5.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.4 Creación del ObjetoButton" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.4.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.3 Creación del ObjetoEditBox" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_3" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.3.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.2 CommonDialogs" 									,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_2" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.2.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.1 Creación del ObjetoBarraProgreso" 				,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_1" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.1.png"),

array(	"Titulo" 	=> "Tutorial C++ 3.0 Introducción al instalador"						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_0" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.3.0.png"),

/*array(	"Titulo" 	=> "DWL 0.96" 														,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "DWL.png"),

array(	"Titulo" 	=> "BubaTronik 0.60" 												,
        "Fecha" 	=> "30/10/2010" ,
        "URL" 		=> "BubaTronik" 										,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "BubaTronik061.png"),*/

array(	"Titulo" 	=> "LMD 0.02a" 														,
        "Fecha" 	=> "01/09/2010" ,
        "URL" 		=> "LMD" 												,
        "Tags" 		=> array("Windows", "Linux", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "LMD.png"),

array(	"Titulo" 	=> "Antivirus Fotos 05/06" 											,
        "Fecha" 	=> "16/06/2010" ,
        "URL" 		=> "Antivirus_Fotos0506" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "FotoVirus0506.png"),

array(	"Titulo" 	=> "DWL 0.95" 														,
        "Fecha" 	=> "31/05/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "DWL.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.6 Terminando el snake" 							,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_6" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Snake.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.5 Creación del ObjetoEscena_Nivel" 				,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_5" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.2.5.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.4 Creación del ObjetoEscena_Records" 				,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.2.4.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.3 Archivos y directorios" 						,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_3" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.2.3.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.2 Tablero, marcador, y mensaje"					,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_2" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.2.2.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.1 Creación del ObjetoEscena" 						,
        "Fecha" 	=> "05/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_1" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.2.1.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.0 Introducción al Snake" 							,
        "Fecha" 	=> "05/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_0" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Snake.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.7 Terminando la calculadora" 						,
        "Fecha" 	=> "14/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_7" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Calculadora.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.6 Creación de un ObjetoMarcador",
        "Fecha" 	=> "14/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_6",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.1.6.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.5 Creación de un ObjetoBoton",
        "Fecha" 	=> "11/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_5",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.1.5.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.4 Entorno gráfico de windows GDI",
        "Fecha" 	=> "08/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_4",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.1.4.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.3 Creación de un ObjetoVentana",
        "Fecha" 	=> "06/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_3",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.1.3.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.2 Creación de Ventanas",
        "Fecha" 	=> "02/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_2",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Ejemplo.1.2.png"),

array(	"Titulo" 	=> "Tutorial C++ 1.1 POO y WinMain",
        "Fecha" 	=> "01/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_1",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "WinMain"),

array(	"Titulo" 	=> "Tutorial C++ 1.0 Introducción a la Calculadora",
        "Fecha" 	=> "01/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_0",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Articulo",
        "Imagen"	=> "Calculadora.png"),


);

?>