<?php
    /* Tipo puede ser : 'Blog', 'Lab', 'DocCSS' */
    /* Las imagenes van sin su tamaño y debe haber una de imagen 155x125_, y una imagen de 250x200_ */ 
    /*  ej: 155x125_CSS3.png, 250x200_CSS3.png */

    /* Ojo! si el titulo no coincide con el titulo de devildrey33::InicioBlog, no se mostrará correctamente la imagen de la portada. */
    return array(        
array(	"Titulo" 	=> "Audio Shader #4",
        "Fecha" 	=> "06/05/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Audio-PlayGround/4/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders", "WebAudio"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "AudioShader4.png"),      
        
array(	"Titulo" 	=> "Audio Shader #3",
        "Fecha" 	=> "27/04/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Audio-PlayGround/3/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders", "WebAudio"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "AudioShader3.png"),      
        
array(	"Titulo" 	=> "Audio Shader #2",
        "Fecha" 	=> "26/04/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Audio-PlayGround/2/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders", "WebAudio"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "AudioShader2.png"),      
        
array(	"Titulo" 	=> "Audio Shader #1",
        "Fecha" 	=> "20/04/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Audio-PlayGround/1/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders", "WebAudio"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "AudioShader1.png"),      
        
        
array(	"Titulo" 	=> "Audio PlayGround",
        "Fecha" 	=> "10/04/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Audio-PlayGround/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders", "WebAudio"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "AudioPlayGround.png"),      
        
array(	"Titulo" 	=> "Portal Experience",
        "Fecha" 	=> "20/03/2023",
        "URL" 		=> "Ejemplos/Three.js-Journey/Portal-Experience/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Shaders"),
        "Tipo"		=> "Experience",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "en",
        "Imagen"	=> "PortalExperience.png"),      
        
array(	"Titulo" 	=> "Chromatic Motion Blur",
        "Fecha" 	=> "18/04/2021",
        "URL" 		=> "Ejemplos/ChromaticMotionBlur/index.html",
        "Tags" 		=> array("CSS", "JavaScript", "Programación"),
        "Tipo"		=> "Lab",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Chroma.png"),      
        
array(	"Titulo" 	=> "Dominó 3D",
        "Fecha" 	=> "16/01/2019",
        "URL" 		=> "Ejemplos/Domino/index.html",
        "Tags" 		=> array("Three.js", "JavaScript", "Programación"),
        "Tipo"		=> "Lab",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Domino.png"),      
        
array(	"Titulo" 	=> "Propiedad CSS : filter",
        "Fecha" 	=> "28/06/2018",
        "URL" 		=> "CSS/Propiedades/filter",
        "Tags" 		=> array("CSS", "HTML"),
        "Tipo"		=> "DocCSS",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),      
        
array(	"Titulo" 	=> "Propiedad CSS : clip-path",
        "Fecha" 	=> "14/06/2018",
        "URL" 		=> "CSS/Propiedades/clip-path",
        "Tags" 		=> array("CSS", "HTML"),
        "Tipo"		=> "DocCSS",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"), 
        
array(	"Titulo" 	=> "Experimento con Three.js 'CyberParasit'", 
        "Fecha" 	=> "30/08/2017",
        "URL" 		=> "Ejemplos/CyberParasit/CyberParasit.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación", "WebAudio" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "CyberParasit.png"),
        
array(	"Titulo" 	=> "Experimento con Three.js 'Hex Tunnel'", 
        "Fecha" 	=> "15/05/2017",
        "URL" 		=> "Ejemplos/BannerTest/HexTunnel.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "HexTunnel.png"),
        
array(	"Titulo" 	=> "Experimento con Three.js 'Espiral RGB'", 
        "Fecha" 	=> "28/04/2017",
        "URL" 		=> "Ejemplos/BannerTest/EspiralRGB.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación", "Shaders" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "EspiralRGB.png"),
        
array(	"Titulo" 	=> "Experimento con Three.js 'EspectroAudible'", 
        "Fecha" 	=> "23/02/2017",
        "URL" 		=> "Ejemplos/BannerTest/EspectroAudible.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación", "WebAudio" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "EspectroAudible.png"),
        
array(	"Titulo" 	=> "Experimento con Three.js 'MultiCubo'", 
        "Fecha" 	=> "26/10/2016",
        "URL" 		=> "Ejemplos/BannerTest/MultiCubo.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "MultiCubo.png"),
        
array(	"Titulo" 	=> "Experimento con Canvas 2D 'Reunion de circulos'", 
        "Fecha" 	=> "26/10/2016",
        "URL" 		=> "Ejemplos/BannerTest/ReunionDeCirculos.html", 
        "Tags" 		=> array("Canvas 2D", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "ReunionDeCirculos.png"),
        
array(	"Titulo" 	=> "Experimento con Three.js 'Esfera (Vertex Shader)'", 
        "Fecha" 	=> "07/10/2016",
        "URL" 		=> "Ejemplos/BannerTest/EsferaVShader.html", 
        "Tags" 		=> array("Three.js", "JavaScript", "Programación", "Shaders" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "EsferaVShader.png"),

array(	"Titulo" 	=> "Experimento con Canvas 2D 'Geometría básica'", 
        "Fecha" 	=> "01/10/2016",
        "URL" 		=> "Ejemplos/BannerTest/GeometriaBasica.html", 
        "Tags" 		=> array("Canvas 2D", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "GeometriaBasica.png"),

array(	"Titulo" 	=> "Experimento con Canvas 2D 'Sinusoidal'", 
        "Fecha" 	=> "07/09/2016",
        "URL" 		=> "Ejemplos/BannerTest/Sinusoidal.html", 
        "Tags" 		=> array("Canvas 2D", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "Sinusoidal.png"),

array(	"Titulo" 	=> "Experimento con Canvas 2D 'Anillos'", 
        "Fecha" 	=> "07/08/2016",
        "URL" 		=> "Ejemplos/BannerTest/Anillos.html", 
        "Tags" 		=> array("Canvas 2D", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "Anillos.jpg"),

array(	"Titulo" 	=> "Experimento con Three.js 'WormHole'", 
        "Fecha" 	=> "03/08/2016",
        "URL" 		=> "Ejemplos/BannerTest/WormHole.html", 
        "Tags" 		=> array("Three js", "JavaScript", "Programación" ),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "WormHole.png"),

array(	"Titulo" 	=> "Experimento con Three.js 'Adiestramiento de cubos'", 
        "Fecha" 	=> "03/08/2016",
        "URL" 		=> "Ejemplos/BannerTest/AdiestramientoCubos.html", 
        "Tags" 		=> array("Three js", "JavaScript", "Programación"),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "Adiestramiento.png"),        
        
array(	"Titulo" 	=> "Referéncia CSS : Variables",
        "Fecha" 	=> "28/06/2016",
        "URL" 		=> "variables-css",
        "Tags" 		=> array("CSS", "JavaScript", "HTML", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"), 
        
array(	"Titulo" 	=> "Algunos efectos para botones en CSS",
        "Fecha" 	=> "16/03/2016",
        "URL" 		=> "algunos-efectos-para-botones-en-css",
        "Tags" 		=> array("CSS", "HTML", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"), 
        
array(	"Titulo" 	=> "Resaltar sintaxis de un código fuente",
        "Fecha" 	=> "29/01/2016",
        "URL" 		=> "resaltar-sintaxis-codigo-fuente",
        "Tags" 		=> array("PHP", "JavaScript", "CSS", "HTML", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ResaltarSintaxis.png"),
        
array(	"Titulo" 	=> "Working with google APIs",
        "Fecha" 	=> "16/12/2015",
        "URL" 		=> "working-with-google-apis",
        "Tags" 		=> array("JavaScript", "HTML", "Programación", "Google api"),
        "Tipo"		=> "Blog",
        "Autor"         => "Joel Barba",
        "Idioma"        => "en",
        "Imagen"	=> "google_apis.jpg"),
        
array(	"Titulo" 	=> "Solitario HTML5", 
        "Fecha" 	=> "16/12/2015",
        "URL" 		=> "Ejemplos/Solitario/Solitario.html", 
        "Tags" 		=> array("JavaScript", "CSS", "HTML", "Programación"),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Lab",
        "Imagen"	=> "Solitario.png"),
        
array(	"Titulo" 	=> "FlexBox para diseños responsive", 
        "Fecha" 	=> "13/12/2015",
        "URL" 		=> "flex-box-y-media-queries",
        "Tags" 		=> array("CSS", "HTML", "Programación", "Responsive"),
        "Idioma"        => "es",
        "Autor"         => "Josep Antoni Bover",
        "Tipo"		=> "Blog",   
        "Imagen"	=> "CSS3.png"),
 
array(	"Titulo" 	=> "How to use google app scripts", 
        "Fecha" 	=> "23/11/2015",
        "URL" 		=> "how-to-use-google-app-scripts",
        "Tags" 		=> array("JavaScript", "HTML", "Programación", "Google app scripts"),
        "Tipo"		=> "Blog",   
        "Autor"         => "Joel Barba",
        "Idioma"        => "en",
        "Imagen"	=> "how-to-use-google-app-scripts.png"),        
        
array(	"Titulo" 	=> "Webs de contenido dinámico", 
        "Fecha" 	=> "19/11/2015",
        "URL" 		=> "webs-contenido-dinamico",
        "Tags" 		=> array("JavaScript", "JQuery", "PHP", "HTML", "Programación"),
        "Tipo"		=> "Blog",   
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "webs-dinamicas.png"),
        
array(	"Titulo" 	=> "Utilizar controles input ocultos asociados a un label.", 
        "Fecha" 	=> "15/09/2015",
        "URL" 		=> "utilizar-controles-input-ocultos-asociados-a-un-label",
        "Tags" 		=> array("CSS", "HTML", "Programación"),
        "Tipo"		=> "Blog",   
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "InputOculto.png"),

array(	"Titulo" 	=> "Notas sobre la actualización de la web",  
        "Fecha" 	=> "07/09/2015",
        "URL" 		=> "notas-actualizacion-web",
        "Tags" 		=> array("HTML", "CSS", "JavaScript", "PHP", "SQL", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Logo.png"),

array(	"Titulo" 	=> "Empezando con SQLite en C++",  
        "Fecha" 	=> "22/05/2014",
        "URL" 		=> "empezando-sqlte-c",
        "Tags" 		=> array("C y C++", "SQL", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Sqlite.png"),

array(	"Titulo" 	=> "Varios ejemplos de menús",
        "Fecha" 	=> "19/02/2014" ,
        "URL" 		=> "varios-ejemplos-de-menus",
        "Tags" 		=> array("CSS", "HTML", "JQuery", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "VariosMenus.png"),

array(	"Titulo" 	=> "Varios servidores web apache de pruebas",
        "Fecha" 	=> "15/02/2014" ,
        "URL" 		=> "varios-servidores-web-apache-de-pruebas",
        "Tags" 		=> array("Apache", "Servidores", "Windows", "Linux"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "XAMPP.png"),

array(	"Titulo" 	=> "Tablas automáticas y tablas fijas",
        "Fecha" 	=> "12/01/2014" ,
        "URL" 		=> "Tablas",
        "Tags" 		=> array("CSS", "HTML", "Programación", "Responsive"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Referéncia CSS : Propiedades",
        "Fecha" 	=> "27/06/2013" ,
        "URL" 		=> "PropiedadesCSS",
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "USB booteable con varios sistemas operativos (ACTUALIZADO)"		,
        "Fecha" 	=> "16/05/2013" ,
        "URL" 		=> "USB_Boot" 										,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "USBBoot.png"),

array(	"Titulo" 	=> "Referéncia CSS : Degradados" 									,
        "Fecha" 	=> "11/03/2013" ,
        "URL" 		=> "DegradadosCSS" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Animaciones CSS3" 												,
        "Fecha" 	=> "29/01/2013" ,
        "URL" 		=> "AnimacionesCSS3" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "devildrey33_ListaDesplegable 2.0 FINAL" 							,
        "Fecha" 	=> "20/01/2013" ,
        "URL" 		=> "devildrey33_ListaDesplegable_2-0" 				,
        "Tags" 		=> array("JavaScript", "HTML", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "devildrey33_ListaDesplegable_2.0.png"),

array(	"Titulo" 	=> "devildrey33_ListaDesplegable 2.0 BETA" 							,
        "Fecha" 	=> "05/01/2013" ,
        "URL" 		=> "devildrey33_ListaDesplegable_2-0_BETA" 			,
        "Tags" 		=> array("JavaScript", "HTML", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "devildrey33_ListaDesplegable_2.0.png"),

array(	"Titulo" 	=> "Referéncia CSS : Unidades" 										,
        "Fecha" 	=> "05/12/2012" ,
        "URL" 		=> "UnidadesCSS"										,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Referéncia CSS : Colores" 										,
        "Fecha" 	=> "04/12/2012" ,
        "URL" 		=> "ColoresCSS"										,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Atributo ContentEditable del HTML" 								,
        "Fecha" 	=> "21/11/2012" ,
        "URL" 		=> "ContentEditable" 									,
        "Tags" 		=> array("JavaScript", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",    
        "Idioma"        => "es",
        "Imagen"	=> "ContentEditable.png"),

array(	"Titulo" 	=> "Añadir más seguridad a nuestro servidor Web" 					,
        "Fecha" 	=> "29/10/2012" ,
        "URL" 		=> "SeguridadServidorWeb" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "Servidores", ".htaccess") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Candado.png"),

array(	"Titulo" 	=> "Referéncia CSS : Selectores" 									,
        "Fecha" 	=> "17/10/2012" ,
        "URL" 		=> "SelectoresCSS" 									,
        "Tags" 		=> array("CSS", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

/*array(	"Titulo" 	=> "USB booteable con varios sistemas operativos" 					,
        "Fecha" 	=> "26/09/2012" ,
        "URL" 		=> "USB_Boot" 										,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "USBBoot.png"),*/

array(	"Titulo" 	=> "DWL 2012" 											,
        "Fecha" 	=> "15/02/2012" ,
        "URL" 		=> "DWL2012-15-02-2012" 								,
        "Tags" 		=> array("C y C++", "Windows", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ataque.png"),

/*array(	"Titulo" 	=> "DWL 2012 [08/02/2012]",
        "Fecha" 	=> "08/02/2012" ,
        "URL" 		=> "DWL2012-08-02-2012" 								,
        "Tags" 		=> array("C y C++", "Windows", "Programación"),	
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "DWL2012.png"),*/

array(	"Titulo" 	=> "Captchas (3 Captcha arrastrar y soltar PHP + JQuery)" 			,
        "Fecha" 	=> "05/12/2011" ,
        "URL" 		=> "Captcha3" 										,
        "Tags" 		=> array("PHP", "JQuery", "Programación", "HTML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Captcha3.png"),

array(	"Titulo" 	=> "Captchas (2 Captcha básico con php)"								,
        "Fecha" 	=> "04/12/2011" ,
        "URL" 		=> "Captcha2" 										,
        "Tags" 		=> array("PHP", "JavaScript", "Programación", "HTML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Captcha2.png"),

array(	"Titulo" 	=> "Captchas (1 Introducción)" 										,
        "Fecha" 	=> "03/12/2011" ,
        "URL" 		=> "Captcha1" 										,
        "Tags" 		=> array("PHP", "JavaScript", "Programación", "HTML") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Captcha.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (9 Tipografías)" 				,
        "Fecha" 	=> "28/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_9" 								,
        "Tags" 		=> array("HTML"), 
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5_9.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (8 Menus)" 					,
        "Fecha" 	=> "22/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_8" 								,
        "Tags" 		=> array("HTML", "CSS"), 
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5_8.png"),

array(	"Titulo" 	=> "Menu PHP + XML + JQuery + JavaScript + Css" 						,
        "Fecha" 	=> "17/11/2011" ,
        "URL" 		=> "MenuWebFijo" 										,
        "Tags" 		=> array("HTML", "PHP", "JQuery", "Programación", "XML") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "MenuWebFijo.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 4 (imagenes)" 						,
        "Fecha" 	=> "16/11/2011" ,
        "URL" 		=> "Canvas2D_4" 										,
        "Tags" 		=> array("Canvas 2D", "HTML", "JavaScript", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Canvas2D_4.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (7 Botones)"					,
        "Fecha" 	=> "15/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_7" 								,
        "Tags" 		=> array("HTML", "CSS"), 
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5_7.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (6 Diseño)" 					,
        "Fecha" 	=> "11/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_6" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (5 Más sobre los estilos)" 	,
        "Fecha" 	=> "10/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_5" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (4 Estilos)" 					,
        "Fecha" 	=> "09/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_4" 								,
        "Tags" 		=> array("HTML", "CSS"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (3 Varias etiquetas)"			,
        "Fecha" 	=> "08/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_3" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (2 Empezando)" 				,
        "Fecha" 	=> "07/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_2" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "Creación de páginas web desde cero (1 Introducción)" 			,
        "Fecha" 	=> "06/11/2011" ,
        "URL" 		=> "Tutorial_HTML5_1" 								,
        "Tags" 		=> array("HTML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "HTML5.png"),

array(	"Titulo" 	=> "CSS3 : Efecto bola expandible" 									,
        "Fecha" 	=> "04/11/2011" ,
        "URL" 		=> "CSS3_BolaExpandible"								,
        "Tags" 		=> array("HTML", "CSS", "Programación"), 
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "BolaExpandible.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 3 (degradado lineal)" 				,
        "Fecha" 	=> "03/11/2011" ,
        "URL" 		=> "Canvas2D_3" 										,
        "Tags" 		=> array("Canvas 2D", "HTML", "JavaScript", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Canvas2D_3.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 2 (texto)" 						,
        "Fecha" 	=> "02/11/2011" ,
        "URL" 		=> "Canvas2D_2" 										,
        "Tags" 		=> array("Canvas 2D", "HTML", "JavaScript", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Canvas2D_2.png"),

array(	"Titulo" 	=> "Tutorial HTML5 Canvas2D parte 1" 								,
        "Fecha" 	=> "31/10/2011" ,
        "URL" 		=> "Canvas2D_1" 										,
        "Tags" 		=> array("Canvas 2D", "HTML", "JavaScript", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Canvas2D_1.png"),

array(	"Titulo" 	=> "CSS3 : Sombras y bordes redondeados" 							,
        "Fecha" 	=> "28/10/2011" ,
        "URL" 		=> "CSS3_Sombras_Bordes" 								,
        "Tags" 		=> array("HTML", "CSS", "Programación"), 
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

/*array(	"Titulo" 	=> "Varios retoques en la web de devildrey33" 						,
        "Fecha" 	=> "27/10/2011" ,
        "URL" 		=> "RetoquesWeb" 										,
        "Tags" 		=> array() ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Tridente.png"),*/

array(	"Titulo" 	=> "Instalar NetBeans y MinGW en Windows" 							,
        "Fecha" 	=> "26/10/2011" ,
        "URL" 		=> "NetBeansWindows"									,
        "Tags" 		=> array("Windows", "C y C++", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "NetBeans.png"),

array(	"Titulo" 	=> "PHP : Objeto devildrey33_PintarCodigo" 							,
        "Fecha" 	=> "25/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_devildrey33_PintarCodigo" 		,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "PHP.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 6 HTML)" 							,
        "Fecha" 	=> "24/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_HTML" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresHTML.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 5 C++)"							,
        "Fecha" 	=> "21/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_CPP" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresCPP.png"),

/*array(	"Titulo" 	=> "Buscador de texto en PHP" 										,
        "Fecha" 	=> "20/10/2011" ,
        "URL" 		=> "BuscadorPHP" 										,
        "Tags" 		=> array("PHP", "HTML", "Programación"),

        "Idioma"        => "es",
        "Tipo"		=> "Blog",
        "Imagen"	=> "BuscarPHP.png"),*/

array(	"Titulo" 	=> "Colorear código con PHP (Parte 4 PHP)" 							,
        "Fecha" 	=> "19/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_PHP" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresPHP.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 3 JavaScript)" 					,
        "Fecha" 	=> "18/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_JavaScript" 					,
        "Tags" 		=> array("PHP", "HTML", "Programación", "JavaScript"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresJavaScript.png"),

array(	"Titulo" 	=> "CSS3 Transition y Transform" 									,
        "Fecha" 	=> "17/10/2011" ,
        "URL" 		=> "CSS3_Transition_Transform"						,
        "Tags" 		=> array("HTML", "Programación", "CSS"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "CSS3.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 2 CSS)" 							,
        "Fecha" 	=> "14/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_CSS" 							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "CSS") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresCSS.png"),

array(	"Titulo" 	=> "Colorear código con PHP (Parte 1 XML)" 							,
        "Fecha" 	=> "13/10/2011" ,
        "URL" 		=> "ColorearCodigoPHP_XML"							,
        "Tags" 		=> array("PHP", "HTML", "Programación", "XML"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ColoresXML.png"),

array(	"Titulo" 	=> "Generar un .lib a partir de una DLL con Visual Studio" 			,
        "Fecha" 	=> "12/10/2011" ,
        "URL" 		=> "GenerarLibDesdeDll" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "GenerarLibDesdeDll.png"),

array(	"Titulo" 	=> "Utilizar archivos XML con PHP" 									,
        "Fecha" 	=> "10/10/2011" ,
        "URL" 		=> "PHPyXML" 											,
        "Tags" 		=> array("PHP", "HTML", "XML", "Programación") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "PHPyXML.png"),

array(	"Titulo" 	=> "Crear servidor web de pruebas portatil para windows" 			,
        "Fecha" 	=> "07/10/2011" ,
        "URL" 		=> "XamppUSB" 										,
        "Tags" 		=> array("Windows", "Servidores", "HTML") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "XAMPP.png"),

array(	"Titulo" 	=> "Creación de feeds RSS" 											,
        "Fecha" 	=> "06/10/2011" ,
        "URL" 		=> "FeedsRSS" 										,
        "Tags" 		=> array("Apache", "PHP", "Programación", "HTML") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "RSS.png"),

array(	"Titulo" 	=> "Tutorial C++ 4 Creación de archivos DUMP"						,
        "Fecha" 	=> "05/10/2011" ,
        "URL" 		=> "Tutorial_WINAPI_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "DUMP.png"),

array(	"Titulo" 	=> "ComboBox PHP + JQuery + JavaScript + Css" 						,
        "Fecha" 	=> "04/10/2011" ,
        "URL" 		=> "ComboBoxWeb" 										,
        "Tags" 		=> array("PHP", "Programación", "JavaScript", "HTML") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ComboBoxWeb.png"),

array(	"Titulo" 	=> "Instalar Ubuntu bajo VirtualBox en Windows" 						,
        "Fecha" 	=> "03/10/2011" ,
        "URL" 		=> "InstalarUbuntuVirtualBox" 						,
        "Tags" 		=> array("Windows", "Linux") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "VirtualBox.png"),

array(	"Titulo" 	=> "WebGL" 															,
        "Fecha" 	=> "10/04/2011" ,
        "URL" 		=> "WebGL" 											,
        "Tags" 		=> array("HTML", "Programación", "JavaScript") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "WebGL.png"),

array(	"Titulo" 	=> "Inyección SQL" 													,
        "Fecha" 	=> "26/02/2011" ,
        "URL" 		=> "InyeccionSQL" 									,
        "Tags" 		=> array("HTML", "Programación", "PHP", "SQL") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "InyeccionSQL.png"),

array(	"Titulo" 	=> "Conversor UTF8 - Windows1252" 										,
        "Fecha" 	=> "07/02/2011" ,
        "URL" 		=> "Conversor_UTF8_Windows1252" 						,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "ConversorUTF8-Windows1252.png"),

array(	"Titulo" 	=> "Comparativa navegadores 2011" 						,
        "Fecha" 	=> "14/01/2011" ,
        "URL" 		=> "ComparativaNavegadoresEnero2011" 					,
        "Tags" 		=> array("HTML", "Programación"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Navegadores.png"),

/*array(	"Titulo" 	=> "DWL 0.961" 														,
        "Fecha" 	=> "27/11/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "DWL.png"),*/

array(	"Titulo" 	=> "BubaTronik 0.61" 												,
        "Fecha" 	=> "26/11/2010" ,
        "URL" 		=> "BubaTronik"										,
        "Tags" 		=> array("Windows", "Programación", "C y C++") ,
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "BubaTronik061.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.11 (Terminando el Ensamblador)" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_11" 							,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.11.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.10 (Terminando el Instalador)" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_10" 							,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.0.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.9 (Creación del ObjetoZLIB)" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_9" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.9.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.8 (Creación del ObjetoTreeView)" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_8" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.8.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.7 (Creación del ObjetoListView)" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_7" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.7.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.6 (Creación del ObjetoProgressBar)" 				,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_6" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.6.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.5 (Creación del ObjetoComboBox)"					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_5" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.5.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.4 (Creación del ObjetoButton)" 						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.4.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.3 (Creación del ObjetoEditBox)" 					,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_3" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.3.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.2 (Common Dialogs)" 									,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_2" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.2.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.1 Creación del ObjetoBarraProgreso" 				,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_1" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.1.png"),

array(	"Titulo" 	=> "Tutorial WinAPI C++ 3.0 (Introducción al Instalador)"						,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "Tutorial_WINAPI_3_0" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.3.0.png"),

/*array(	"Titulo" 	=> "DWL 0.96" 														,
        "Fecha" 	=> "06/11/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "DWL.png"),

array(	"Titulo" 	=> "BubaTronik 0.60" 												,
        "Fecha" 	=> "30/10/2010" ,
        "URL" 		=> "BubaTronik" 										,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "BubaTronik061.png"),*/

array(	"Titulo" 	=> "LMD 0.02a (Libreria Multiplataforma Devildrey33)" 														,
        "Fecha" 	=> "01/09/2010" ,
        "URL" 		=> "LMD" 												,
        "Tags" 		=> array("Windows", "Linux", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "LMD.png"),

array(	"Titulo" 	=> 'Aplicación para eliminar el virus &quot;Fotos 05/06&quot;' 											,
        "Fecha" 	=> "16/06/2010" ,
        "URL" 		=> "Antivirus_Fotos0506" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "FotoVirus0506.png"),

array(	"Titulo" 	=> "Devildrey33 Windows Library" 														,
        "Fecha" 	=> "31/05/2010" ,
        "URL" 		=> "DWL" 												,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "DWL.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.6 (Terminando el Snake)" 							,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_6" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Snake.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.5 (Creación del ObjetoSnake_Nivel)" 				,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_5" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.2.5.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.4 (Crear ObjetoEscena_Records)" 				,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_4" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.2.4.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.3 (Archivos y directorios)" 						,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_3" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.2.3.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.2 Crear tablero, marcador y mensaje"					,
        "Fecha" 	=> "14/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_2" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.2.2.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 2.1 (Creación del ObjetoEscena)" 						,
        "Fecha" 	=> "05/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_1" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.2.1.png"),

array(	"Titulo" 	=> "Tutorial C++ 2.0 Introducción al Snake" 							,
        "Fecha" 	=> "05/05/2010" ,
        "URL" 		=> "Tutorial_WINAPI_2_0" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Snake.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.7 (Terminando la calculadora)" 						,
        "Fecha" 	=> "14/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_7" 								,
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Calculadora.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.6 (Creación del ObjetoMarcador)",
        "Fecha" 	=> "14/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_6",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.1.6.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.5 (Creación de nuestro ObjetoBoton)",
        "Fecha" 	=> "11/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_5",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.1.5.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.4 (Entorno gráfico de windows GDI)",
        "Fecha" 	=> "08/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_4",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.1.4.png"), 

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.3 (Creación de un ObjetoVentana)",
        "Fecha" 	=> "06/04/2010" , 
        "URL" 		=> "Tutorial_WINAPI_1_3",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.1.3.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.2 (Creación de una ventana)",
        "Fecha" 	=> "02/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_2",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Ejemplo.1.2.png"),

array(	"Titulo" 	=> "Tutorial WINAPI C++ 1.1 (POO y WinMain)",
        "Fecha" 	=> "01/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_1",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "WinMain.png"),
 
array(	"Titulo" 	=> "Tutorial C++ 1.0 Introducción a la Calculadora",
        "Fecha" 	=> "01/04/2010" ,
        "URL" 		=> "Tutorial_WINAPI_1_0",
        "Tags" 		=> array("Windows", "Programación", "C y C++"),
        "Tipo"		=> "Blog",
        "Autor"         => "Josep Antoni Bover",
        "Idioma"        => "es",
        "Imagen"	=> "Calculadora.png"),

);

?>